version: '3.7'
services:

  api:
    build:
      context: ./backend
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./backend:/code
    ports:
      - 5000:5000
    env_file:
      - .env

  cache:
    image: memcached:latest
    restart: unless-stopped
    ports:
      - 11211:11211
    entrypoint:
      - memcached
      - -m 128