# Generated by Django 4.1.3 on 2023-05-29 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer_peos'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('total_accepted_answers', models.IntegerField(default=0)),
                ('accepted_answers_average_score', models.FloatField(default=0.0)),
                ('average_answers_per_question', models.FloatField(default=0.0)),
                ('top_ten_answers_comment_count', models.JSONField()),
            ],
            options={
                'verbose_name': 'StatResults',
                'verbose_name_plural': 'StatResults',
                'ordering': ['total_accepted_answers'],
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='peos',
        ),
    ]
